
package br.edu.ifms.clientsoap2.servico;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SEIClient", targetNamespace = "http://servico.clientsoap.ifms.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SEIClient {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adicionar", targetNamespace = "http://servico.clientsoap.ifms.edu.br/", className = "br.edu.ifms.clientsoap2.servico.Adicionar")
    @ResponseWrapper(localName = "adicionarResponse", targetNamespace = "http://servico.clientsoap.ifms.edu.br/", className = "br.edu.ifms.clientsoap2.servico.AdicionarResponse")
    @Action(input = "http://servico.clientsoap.ifms.edu.br/SEIClient/adicionarRequest", output = "http://servico.clientsoap.ifms.edu.br/SEIClient/adicionarResponse")
    public boolean adicionar(
        @WebParam(name = "arg0", targetNamespace = "")
        Client arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifms.clientsoap2.servico.Client>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listar", targetNamespace = "http://servico.clientsoap.ifms.edu.br/", className = "br.edu.ifms.clientsoap2.servico.Listar")
    @ResponseWrapper(localName = "listarResponse", targetNamespace = "http://servico.clientsoap.ifms.edu.br/", className = "br.edu.ifms.clientsoap2.servico.ListarResponse")
    @Action(input = "http://servico.clientsoap.ifms.edu.br/SEIClient/listarRequest", output = "http://servico.clientsoap.ifms.edu.br/SEIClient/listarResponse")
    public List<Client> listar();

}
