
package br.edu.ifms.clientsoap2.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "SIBClientService", targetNamespace = "http://servico.clientsoap.ifms.edu.br/", wsdlLocation = "http://localhost:8088/clientsoap?wsdl")
public class SIBClientService
    extends Service
{

    private final static URL SIBCLIENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIBCLIENTSERVICE_EXCEPTION;
    private final static QName SIBCLIENTSERVICE_QNAME = new QName("http://servico.clientsoap.ifms.edu.br/", "SIBClientService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/clientsoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIBCLIENTSERVICE_WSDL_LOCATION = url;
        SIBCLIENTSERVICE_EXCEPTION = e;
    }

    public SIBClientService() {
        super(__getWsdlLocation(), SIBCLIENTSERVICE_QNAME);
    }

    public SIBClientService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIBCLIENTSERVICE_QNAME, features);
    }

    public SIBClientService(URL wsdlLocation) {
        super(wsdlLocation, SIBCLIENTSERVICE_QNAME);
    }

    public SIBClientService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIBCLIENTSERVICE_QNAME, features);
    }

    public SIBClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIBClientService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SEIClient
     */
    @WebEndpoint(name = "SIBClientPort")
    public SEIClient getSIBClientPort() {
        return super.getPort(new QName("http://servico.clientsoap.ifms.edu.br/", "SIBClientPort"), SEIClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SEIClient
     */
    @WebEndpoint(name = "SIBClientPort")
    public SEIClient getSIBClientPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.clientsoap.ifms.edu.br/", "SIBClientPort"), SEIClient.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIBCLIENTSERVICE_EXCEPTION!= null) {
            throw SIBCLIENTSERVICE_EXCEPTION;
        }
        return SIBCLIENTSERVICE_WSDL_LOCATION;
    }

}
